name: build container
on: 
  # triggered by user action only
  workflow_dispatch:
    inputs:
      PG_VERSION:
        description: 'Postgres version'
        required: true
        default: '17'

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v3
      # authenticate ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set sha-short
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: calculate image tag
      id: vars
      run: |
        echo "IMAGE_TAG=${{ github.event.inputs.PG_VERSION }}" >> $GITHUB_OUTPUT
    - uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/postgresql:${{ steps.vars.outputs.IMAGE_TAG }}-${{ env.GITHUB_SHA_SHORT }}
        build-args: |
          POSTGRESQL_VERSION=${{ github.event.inputs.PG_VERSION }}